// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7tfV6Hibe4e10T1yeaCIlXsvzpFpNtc',
    appId: '1:881019176288:web:2f2a586dd9de1d07f0ca05',
    messagingSenderId: '881019176288',
    projectId: 'cmsc23-todo-app-bmpineda',
    authDomain: 'cmsc23-todo-app-bmpineda.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-bmpineda.appspot.com',
    measurementId: 'G-N5Q737EN4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASA_6jWBF80JXz_O5ELUXOM91BxABVSo8',
    appId: '1:881019176288:android:0e525abc55600a43f0ca05',
    messagingSenderId: '881019176288',
    projectId: 'cmsc23-todo-app-bmpineda',
    storageBucket: 'cmsc23-todo-app-bmpineda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbWE_OIAw-2nMSuAZLifhbigz7G9MJBRo',
    appId: '1:881019176288:ios:82f58c5f5daa69e3f0ca05',
    messagingSenderId: '881019176288',
    projectId: 'cmsc23-todo-app-bmpineda',
    storageBucket: 'cmsc23-todo-app-bmpineda.appspot.com',
    iosClientId: '881019176288-h0l8i1tfqj4928b8pcb7uplou2oce3h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbWE_OIAw-2nMSuAZLifhbigz7G9MJBRo',
    appId: '1:881019176288:ios:82f58c5f5daa69e3f0ca05',
    messagingSenderId: '881019176288',
    projectId: 'cmsc23-todo-app-bmpineda',
    storageBucket: 'cmsc23-todo-app-bmpineda.appspot.com',
    iosClientId: '881019176288-h0l8i1tfqj4928b8pcb7uplou2oce3h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
